remote_theme: pages-themes/cayman@v0.2.0

title: Spacebound Minds
author:
  name: Spacebound Minds
  email: eileen.xu@ed.ac.uk

description: >
  Online resources for you to learn more about mental health and well-being!

header_pages:
  - another-page.md

plugins:
  - jekyll-remote-theme
