remote_theme: jekyll/minima

title: Spacebound Minds online resources
author:
  name: Spacebound Minds
  email: someone@ed.ac.uk

description: >
  An awesome description of Spacebound Minds and our awesome resources goes here.

header_pages:
  - index.md
  - another-page.md

minima:
  skin: solarized
  
