remote_theme: pages-themes/cayman@v0.2.0

title: Spacebound Minds online resources
author:
  name: Spacebound Minds
  email: someone@ed.ac.uk

description: >
  Mission control have sorted out the basics — food, water, air — but the rest is up to you!

header_pages:
  - another-page.md

plugins:
  - jekyll-remote-theme
