remote_theme: pages-themes/cayman@v0.2.0

title: Spacebound Minds online resources
author:
  name: Spacebound Minds
  email: someone@ed.ac.uk

description: >
  An awesome description of Spacebound Minds and our awesome resources goes here.

header_pages:
  - another-page.md

plugins:
  - jekyll-remote-theme
